apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-website
  template:
    metadata:
      labels:
        app: front-website
    spec:
      containers:
      - name: front-website
        image: deenamanick/pipeline_demo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-website
spec:
  type: NodePort
  selector:
    app: front-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
